Feat: Image Pull Secrets
devopzilla/guku-devx-catalog pull request #12
Opened 2023-05-21 13:18 UTC by ahmedhesham6

- Add Helm Values Config

2023-05-21 17:55 UTC, kajogo777 requested changes

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		revision: ""
this doesn't allow people to override this value maybe change it to `string | *""`

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	podAnnotations: {}
this doesn't allow people to override this value maybe change it to `[string]: string`

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		seccompProfile: {
this is also a literal value, it should be a schema with a default value

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +			drop: ["ALL"]
same issue

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		repository: "ghcr.io/banzaicloud/imagepullsecrets"
same issue, it should be a schema and a default value `string | *"ghcr.io/banzaicloud/imagepullsecrets"`

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	imagePullSecrets: []
what's the schema of this field?

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	nodeSelector: {string: string} | *{}
is this valid cue?

2023-05-21 17:55 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	nodeSelector: {string: string} | *{}
I think it should be `{[string]: string}`

2023-05-21 18:07 UTC, ahmedhesham6 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	imagePullSecrets: []
Not shown in the file

2023-05-22 09:11 UTC, kajogo777 requested changes

2023-05-22 09:11 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	podSecurityContext: v1.#PodSecurityContext | *{
since you set the schema the default values can be concrete 3ady

for example `true` is fine, you don't have to add `bool | *true`

2023-05-22 09:11 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		namespaces:         {string: string} | *{}
a map should be [string]: string, and you don't have to add a default empty map CUE does this by default

are you sure namespaces is a map?

2023-05-22 09:11 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		namespacesWithPods: [string] | *[]
[string] is a single item list, if you want to define a list it should be [...string], and you don't have to add a default empty list CUE does this by default

2023-05-22 09:11 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		credentials:        [string] | *[]
[string] is a single item list, if you want to define a list it should be [...string], and you don't have to add a default empty list CUE does this by default

2023-05-22 09:11 UTC, kajogo777 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		secretData: {string: string} | *{}
a map should be [string]: string, and you don't have to add a default empty map CUE does this by default

2023-05-22 12:05 UTC, ahmedhesham6 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +	nodeSelector: k8s.#Labels
In eso package you used k8s.#Labels as nodeSelector so I added it as eso package was my reference

2023-05-22 12:06 UTC, ahmedhesham6 commented on k8s/services/imagepullsecrets/helm-0.3.cue
> +		tlsConfig:      {string: string} | *{}
not mentioned in the chart values

2023-05-22 12:20 UTC, merged