Feat: RabbitMQ Operator
devopzilla/guku-devx-catalog pull request #19
Opened 2023-06-08 15:28 UTC by ahmedhesham6

2023-06-08 16:48 UTC, kajogo777 requested changes
There are some concrete fields that cannot be changed by end-users, these should be turned into a schema/constraint with a default value.

I suspect there's  a field with the wrong schema that should be updated "kubeVersion"

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		imageRegistry: ""
this should be a string with a default value

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		storageClass: ""
this should be a string with a default value

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		storageClass: ""
`string | *""`

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	clusterDomain:     "cluster.local"
this should be a string with a default value `"cluster.local"`

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	kubeVersion:       #KubeVersion
are you sure this is right? we invented the `#KuberVersion` schema for our usage

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	extraDeploy: []
this should be a list of something e.g. `[...string]`

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		topologySpreadConstraints: []
what's the schema?

if it's not know we can leave it as anything `[..._]`

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		hostAliases: []
what's the schema? maybe `[...string]`

if it's not know we can leave it as anything `[..._]`

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		updateStrategy: {
this should be a schema with a default value, the way it's defined now users will not be able to override this value

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		lifecycleHooks: {}
what's the schema? 

the way this is defined now users will not be able to override the value

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		extraEnvVars: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		extraVolumes: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		initContainers: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		image: {
this cannot be changed by end users, for every string field use `string | *"default value"`

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		topologySpreadConstraints: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		hostAliases: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		sidecars: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		initContainers: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +			loadBalancerSourceRanges: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +			sessionAffinityConfig: {}
missing schema

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	selector: {}
missing schema

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	honorLabels: false
this value is concrete, use `bool | *false` instead

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	relabelings: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	labels: {}
missing schema

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	extraPorts: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-08 16:48 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +	loadBalancerSourceRanges: []
what's the schema? maybe [...string]

if it's not know we can leave it as anything [..._]

2023-06-09 14:35 UTC, kajogo777 requested changes

2023-06-09 19:19 UTC, ahmedhesham6 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		"prometheus.io/port":   #Metrics.service.port
We want it referenced to a value

2023-06-09 20:33 UTC, kajogo777 commented on k8s/services/rabbitmq/helm-3.4.cue
> +		"prometheus.io/port":   #Metrics.service.port
then just use `port`

2023-06-11 10:42 UTC, kajogo777 approved these changes

2023-06-11 10:43 UTC, merged